### ISSUE TITLE
Bad request for synced boards

### ISSUE THREAD

**Issue by lrusso96** [jglo-team/JGlo#3]
I cannot create cards nor see the cards already created for synced boards. A bad request message is the only output I can see on PyCharm, Windows.

![image](https://user-images.githubusercontent.com/26090639/56605874-5b0da000-6605-11e9-905c-d4687a782767.png)

**Comment by AlexXandreE** [comment]
Hi, thanks for reporting this error.

I can confirm this is happening even in other systems like Linux.
We will look into this as soon as possible.

**Comment by AlexXandreE** [comment]
Hi again @lrusso96 ,

Got the response from Glo support and it seems their API does not support synced boards yet.
I will add this as a feature request and not a bug (as Glo API was the start of this project).
We will need to connect to users Github account to be able to link the two.

**Comment by Alex-Blanes** [comment]
Hello,
I'm having a similar problem with IntelliJ 2019.4.
It returns "Bad Request" when I try to add or update a card.
Otherwise, I can remove cards, add columns, create and remove boards.
I tried with 1.10, 1.09 and 1.08 versions.
Is there any way to verbose the error?
Thanks in advance

**Comment by AlexXandreE** [comment]
Hi @LaGallinaTuruleta ,

We will look into it as soon as possible.
I have noticed that it happens with every card.

Thanks for submiting the issue.

**Comment by AlexXandreE** [comment]
Just submited the fixed version to the JetBrains market.
It may take some time to appear in the IDE.

Meanwhile you can download the .jar in: [JGlo releases](https://github.com/jglo-team/JGlo/releases/tag/v1.10.2) and do a manual installation on the IDE that you are using.

Thanks again.

**Comment by Alex-Blanes** [comment]
> 
> 
> Just submited the fixed version to the JetBrains market.
> It may take some time to appear in the IDE.
> 
> Meanwhile you can download the .jar in: [JGlo releases](https://github.com/jglo-team/JGlo/releases/tag/v1.10.2) and do a manual installation on the IDE that you are using.
> 
> Thanks again.

All working now, thanks!
I found a good feature that will be great:
Undo
I just removed one card and there isn't a way back. I tried to use Gitkraken undo button but It didn't work.

**Comment by lrusso96** [comment]
> I found a good feature that will be great:
> Undo
> I just removed one card and there isn't a way back. I tried to use Gitkraken undo button but It didn't work.

I think you should open a new issue for that. Since the current issue seems fixed I'm going to close this.
