### ISSUE TITLE
JGlo incompatible with Jetbrains 2019.2 products.

### ISSUE THREAD

**Issue by Scarjit** [jglo-team/JGlo#6]
It seems like JGlo is incompatible with the most recent 2019.2 Versions of Jetbrains IDE's.

Tested with:
 - CLion 2019.2
 - PyCharm 2019.2

JGlo is not showing up in the marketplace, nor is it possible to install the .jar file.
Tested v1.05 (latest on jetbrains) and v1.06 (latest on github)

**Comment by AlexXandreE** [comment]
Hi, 

Thanks for the feedback.

I just need to change the supported versions and re-upload it.
We actually have a little more time at our hands, so expect updates soon :D

**Comment by AlexXandreE** [comment]
Can you try this one:

https://github.com/jglo-team/JGlo/releases/tag/v1.07

Haven't done tests so I hope that it's all Ok.

**Comment by Scarjit** [comment]
Works fine !

**Comment by rudimusmaximus** [comment]
Nothing to show message in WebStorm 2019.2

tried restarting, etc. installed from inside WebStorm plugins.

I see the api does not yet support synced boards per #3 .

That said, I do not see a toolbar when i enable the plugin.
<img width="458" alt="Screen Shot 2019-11-06 at 12 17 19 PM" src="https://user-images.githubusercontent.com/21182598/68325638-71ee7e00-008f-11ea-818f-b073393d468d.png">

**Comment by AlexXandreE** [comment]
Hi @rudimusmaximus ,

Did you login?
You need to go to Tools->Jglo->login.

We need to improve this plugin, as it may not be the most intuitive.
Can i add a popup form as a feature request?

Thanks

**Comment by rudimusmaximus** [comment]
Thanks for the fast reply. Yes, that was the issue. I'm looking forward to future versions as one is needed in the IDEs. Atom editor had a nice one, but I've moved to WebStorm IDE.  At any rate, my biggest need is to have the markdown checkboxes so I can document my progress against the synced GitHub hosted issue/ticket.  Thank you!

**Comment by rudimusmaximus** [comment]
Also, in the IDE I searched for all and then for jglo to see actions; if it was there and maybe in configuration settings or even simple message in the welcome screen would all work to point out not logged in. Anyway, a good idea for a plugin. Best of luck
