### ISSUE TITLE
JGlo options does not appear in CLion

### ISSUE THREAD

**Issue by arlllk** [jglo-team/JGlo#7]
I can't login into my account in JGlo, because it doesn't appear the menu in Configuration -> Tools

[Tool windows](https://i.imgur.com/HhTDd9Y.png)
[Plugins window](https://i.imgur.com/ANmKiKR.png)
[Clion About window](https://i.imgur.com/doJf8KW.png)

In a Windows 10 Version 2004

**Comment by AlexXandreE** [comment]
Hi,
Thanks for taking your time to report :)

It is "hidden" in the top tools option.

![image](https://user-images.githubusercontent.com/26526978/71755423-6ac2d100-2e82-11ea-9803-6eefa504d7ea.png)

We want to update the plugin to prompt for login, as soon as we update it I will notify you :)

**Comment by arlllk** [comment]
Thank, i feel pretty dumb now, closing.

**Comment by AlexXandreE** [comment]
Happens, it means that it was not explicit enough :)
